"""add new column error_message to table

Revision ID: fcc34ddf0d13
Revises: 8a297c896be9
Create Date: 2026-08-11 12:58:46.844733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc34ddf0d13'
down_revision: Union[str, Sequence[str], None] = '8a297c896be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'error_message')
    # ### end Alembic commands ###
